# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define :pvclienteUbuntu do |pvclienteUbuntu|
    pvclienteUbuntu.vm.box = "bento/ubuntu-20.04"
    pvclienteUbuntu.vm.network :private_network, ip: "192.168.200.3"
    pvclienteUbuntu.vm.hostname = "pvclienteUbuntu"
  end

  config.vm.define :pvservidorUbuntu do |pvservidorUbuntu|
    pvservidorUbuntu.vm.box = "bento/ubuntu-20.04"
    pvservidorUbuntu.vm.network :private_network, ip: "192.168.200.2"
    pvservidorUbuntu.vm.hostname = "pvservidorUbuntu"
  end
end